refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} [{t}] {l} {M}:{m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: debug
  app::requests:
    level: debug
    appenders:
      - requests
    additive: true