[package]
name = "fast_admin"
version = "0.1.0"
authors = ["by965738071@163.com <by965738071@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_common  ={path = "../fast_common"}
#log日志支持(必须)
log = "0.4"
fast_log="1.2.9"
env_logger = "0.8"
actix-web = "3.3.2"
actix-http = "2.2.0"
#时间
chrono ="0.4.19"
#orm
rbatis =  { version = "1.8",features=["snowflake","debug_mode"]}
#cpu_count
num_cpus = "1.13.0"
#redis
redis = { version = "0.19.0", features = ["async-std-comp"] }
