[package]
name = "fast_admin"
version = "0.1.0"
authors = ["by965738071@163.com <by965738071@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_common  ={path = "../fast_common"}
#log日志支持(必须)
log = "0.4"

actix-web = "4.0.1"
actix-http = "2.2.0"
#时间
chrono ="0.4.19"
#orm
rbatis = { version = "3.1.6", features = ["debug_mode"] }
rbson = { version = "*" }
#cpu_count
num_cpus = "1.13.0"
async-trait = "0.1.48"
#redis
#redis = { version = "0.17.0", features = ["async-std-comp"] }
serde = { version = "1.0", features = ["derive"] }