[package]
name = "fast_demo"
version = "0.1.0"
authors = ["baiyu <by965738071@163>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12"
hound = "3.4.0"