[package]
name = "fast_demo"
version = "0.1.0"
authors = ["baiyu <by965738071@163>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config_struct = {version= "0.5.0",features = ["toml-parsing"]}
chrono = "0.4.19"